### ISSUE TITLE
go test fails with SIGSEGV 

### ISSUE THREAD

**Issue by pymnh** [newrelic/go-agent#413]
## Description

Package fails to build on the Debian build servers due to an error running `TestConnectAttemptSuccess` in `v3/newrelic/collector_test.go`.

[See the full build log here](https://buildd.debian.org/status/fetch.php?pkg=golang-github-newrelic-go-agent&arch=all&ver=3.15.1-1&stamp=1637421276&raw=0)

```
=== RUN   TestConnectAttemptSuccess
--- FAIL: TestConnectAttemptSuccess (0.11s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x6da518]

goroutine 85 [running]:
testing.tRunner.func1.2({0xa3b2a0, 0x10b1f10})
	/usr/lib/go-1.17/src/testing/testing.go:1209 +0x24e
testing.tRunner.func1()
	/usr/lib/go-1.17/src/testing/testing.go:1212 +0x218
panic({0xa3b2a0, 0x10b1f10})
	/usr/lib/go-1.17/src/runtime/panic.go:1038 +0x215
github.com/newrelic/go-agent/v3/internal/utilization.gatherWithClient.func1({0xaf6ef1, 0x9}, {0xbd1600, 0xc000032280})
	/<<PKGBUILDDIR>>/_build/src/github.com/newrelic/go-agent/v3/internal/utilization/utilization.go:131 +0x118
github.com/newrelic/go-agent/v3/internal/utilization.gatherWithClient({0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, {0x0, 0x0}, ...}, ...)
	/<<PKGBUILDDIR>>/_build/src/github.com/newrelic/go-agent/v3/internal/utilization/utilization.go:142 +0x196
github.com/newrelic/go-agent/v3/internal/utilization.Gather(...)
	/<<PKGBUILDDIR>>/_build/src/github.com/newrelic/go-agent/v3/internal/utilization/utilization.go:117
github.com/newrelic/go-agent/v3/newrelic.config.createConnectJSON({{{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, 0x0, 0x0, 0x0, {0x0, ...}, ...}, ...}, ...)
	/<<PKGBUILDDIR>>/_build/src/github.com/newrelic/go-agent/v3/newrelic/config.go:754 +0x26f
github.com/newrelic/go-agent/v3/newrelic.connectAttempt({{{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, 0x0, 0x0, 0x0, {0x0, ...}, ...}, ...}, ...)
	/<<PKGBUILDDIR>>/_build/src/github.com/newrelic/go-agent/v3/newrelic/collector.go:296 +0x5b8
github.com/newrelic/go-agent/v3/newrelic.testConnectHelper({{0xc00036c090, {0x0, 0x0}}, {0xc00036c120, {0x0, 0x0}}, {{{0x0, 0x0}, {0x0, 0x0}, ...}, ...}})
	/<<PKGBUILDDIR>>/_build/src/github.com/newrelic/go-agent/v3/newrelic/collector_test.go:240 +0x1c5
github.com/newrelic/go-agent/v3/newrelic.TestConnectAttemptSuccess(0xc000001a00)
	/<<PKGBUILDDIR>>/_build/src/github.com/newrelic/go-agent/v3/newrelic/collector_test.go:244 +0x1ee
testing.tRunner(0xc000001a00, 0xb33868)
	/usr/lib/go-1.17/src/testing/testing.go:1259 +0x102
created by testing.(*T).Run
	/usr/lib/go-1.17/src/testing/testing.go:1306 +0x35a
FAIL	github.com/newrelic/go-agent/v3/newrelic	0.143s
```

## Steps to Reproduce

I cannot reproduce this error on a build container on my own machine (also amd64), I am not sure why that is so.

## Expected Behavior

No Segmentation violation should occur

## Your Environment

See the build log (grep for `go env`)

**Comment by RichVanderwal** [comment]
Hi @pymnh , we're wondering if this is an error in the tests due to the sandboxed environment that the Debian package builder runs within. Have you perhaps tried building it locally with no network connected? Let us know if you've discovered anything new about this situation.

**Comment by pymnh** [comment]
@RichVanderwal you are right, this is caused by the sandboxed environment with no network connection and hence a downstream issue, sorry for the noise! I have patched the Debian build to skip the affected tests
